-- Run migration 006 first (confirmation_whatsapp_sent column).
--
-- AUTO-SEND WhatsApp when you set payment_verified = true in Supabase:
-- 1. Supabase Dashboard → Database → Webhooks → Create webhook
-- 2. Table: public.orders | Events: UPDATE
-- 3. URL: https://maajaanki-backend.vercel.app/api/webhooks/supabase/orders
-- 4. HTTP Headers:
--      Authorization: Bearer maajaanki-admin-verify-2026
--    (or set SUPABASE_WEBHOOK_SECRET on Vercel and use that value)
-- 5. Save
--
-- After this, any UPDATE on public.orders triggers:
-- - payment_verified → true: "Order Confirmed" WhatsApp (once per order)
-- - order_status → out_for_delivery: "out for delivery" WhatsApp (once per order)
--
-- Run migrations 009, 010, and 011 (pg_net trigger) for full auto-send.
-- Or call POST /api/admin/orders/out-for-delivery from the dashboard tick.
